name: CI devops 2024

on:
  # Le workflow se déclenche sur un push ou une pull request vers les branches "main" et "dev"
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test-backend:
    # Le job s'exécute sur une machine virtuelle avec Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      # Étape 1 : Vérifier le code source en utilisant l'action officielle "checkout"
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Étape 2 : Configurer le JDK version 17 avec la distribution Corretto (Java d'Amazon)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Étape pour construire et tester l’application avec Maven
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=hul12_tp2 -Dsonar.organization=hul12 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml

