name: CI devops 2024

on:
  # Le workflow se déclenche sur les branches main et dev
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Étape pour vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Étape pour configurer le JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Étape pour construire et tester l’application avec Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

  build-and-push-docker-image:
    needs: test-backend  # Ce job dépend du job test-backend
    runs-on: ubuntu-22.04

    steps:
      # Étape pour vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Étape pour se connecter à Docker Hub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Étape pour construire et pousser l'image du backend
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api  # Chemin vers votre Dockerfile pour le backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Publie uniquement sur la branche main

      # Étape pour construire et pousser l'image de la base de données
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database  # Chemin vers votre Dockerfile pour la base de données
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Publie uniquement sur la branche main

      # Étape pour construire et pousser l'image httpd
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./htt-server  # Chemin vers votre Dockerfile pour httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-htt-server:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Publie uniquement sur la branche mains